### ISSUE TITLE
Not able to use cell_types = "all"

### ISSUE THREAD

**Issue by JH1606-code** [grisslab/scAnnotatR#5]
Hi,

thanks for this nice tool but I have a problem to do the analysis of my data with the parameter cell_types = "all". 
If I use your test sample of the tutorial (https://bioconductor.org/packages/devel/bioc/vignettes/scAnnotatR/inst/doc/classifying-cells.html) with the following parameter everything went fine:

seurat.obj <- classify_cells(classify_obj = tirosh_mel80_example, 
                             assay = 'RNA', slot = 'counts',
                             cell_types = c('B cells', 'NK', 'T cells'), 
                             path_to_models = 'default')

But if I change the cell_types to "all" then I get the following error:

seurat.obj <- classify_cells(classify_obj = tirosh_mel80_example, 
                             assay = 'RNA', slot = 'counts',
                             cell_types = 'all',
                             path_to_models = 'default')

Error: 
snapshotDate(): 2021-10-20
loading from cache
Error in marker_genes(x) : 
  try to request a slot "marker_genes" from an object of simple class ("NULL") without slots

Do you have any idea how to fix this problem?

Best

**Comment by nttvy** [comment]
Hi @JH1606-code 

Thanks for having been interested in our tool. This problem is because a large number of features in the tirosh_mel80_example were removed, in order to have a small enough dataset ship with the package. To make the vignettes work, the remained features are the ones used by those three models (B cells, T cells and NK).

To use all the classifiers, I suggest you use another (public) dataset where there are features available for other cell-type classifiers.

Hope this helps.
Bests,
Vy

**Comment by JH1606-code** [comment]
Thanks for your fast answer. This helps a lot!
