### ISSUE TITLE
slot to use for classify_cells function

### ISSUE THREAD

**Issue by qindan2008** [grisslab/scAnnotatR#6]
Hi,
I wonder which data to use as slot parameter for classify_cells function?
In the tirosh_mel80_example, slot ="count", but  the count matrix was not integer.
So, which slot should be used?  "data" or "count"?
Thank you!

**Comment by nttvy** [comment]
Hi @qindan2008 

Thank you for having been interested in scAnnotatR. The slot can be either 'data' or 'count' or any other newly created slots, because the expression will then be scaled by genes. The example was actually in normalized data, but we transferred it to 'count' slot to reduce the size of the Seurat object.

Wish my answer helps.
Best regards,
Vy

**Comment by qindan2008** [comment]
OK, thank you very much!

**Comment by nttvy** [comment]
I guess this issue has been successfully solved, so I close it. Please reopen it if needed.
